baseURL: https://www.daangeijs.nl
languageCode: en-us
title: Daan Geijs
theme: "PaperModX"

outputs:
  home:
    - HTML
    - RSS
    - JSON # Required for search

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: /posts/:filename/

pluralizelisttitles: "false"

mainSections:
  - posts

params:
  title: Daan Geijs
  description: "Daan Geijs' personal website "
  author: "Daan Geijs"
  DateFormat: " 2 January, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  hideFooter: false
  ShowReadingTime: true
  ShowShareButtons: true
  EnableImageZoom: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowAuthor: true
  ShowCommentNumber: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  TocSide: 'left'
  tocopen: true
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0

  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "favicon.ico"
    appleTouchIcon: "favicon-152.png"

  profileMode:
    enabled: true

paginate: 5
menu:
  main:
  - name: Posts
    url: /posts/
    weight: -150
  - name: Search
    url: /search/
    weight: -90
  - name: Tags
    url: /tags/
    weight: -110
  - name: Archive
    url: /archives/
    weight: -130
  - name: Publications
    url: /publications/
    weight: -140