baseURL: https://www.daangeijs.nl
languageCode: en-us
title: Daan Geijs
theme: "PaperModX"

outputs:
  home:
    - HTML
    - RSS
    - JSON # Required for search

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: /posts/:filename/

pluralizelisttitles: "false"

mainSections:
  - posts
  - media

params:
  title: Daan Geijs
  description: "Daan Geijs' personal website "
  author: "Daan Geijs"
  DateFormat: " 2 January, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  hideFooter: false
  ShowReadingTime: true
  ShowShareButtons: true
  EnableImageZoom: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowAuthor: true
  ShowCommentNumber: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  TocSide: 'left'
  tocopen: true
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "favicon.ico"
    appleTouchIcon: "favicon-152.png"

  profileMode:
    enabled: true
    title: "Daan Geijs"
    subtitle: "PhD candidate @ Computational Pathology Group  \n 
    \n| Working on deep learning for skin cancer assessment |"
    imageUrl: "images/z4d4.jpg"
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
#    buttons:
#      - name: "Publications"
#        url: "publications"
#      - name: "About me"
#        url: "aboutme"
#      - name: "Contact"
#        url: "contact"

  socialIcons:
    - name: github-simple
      url: "https://github.com/daangeijs"
    - name: linkedin-simple
      url: "https://www.linkedin.com/in/daan-geijs-188009121/"
    - name: googlescholar
      url: "https://scholar.google.nl/citations?user=qj6BUocAAAAJ&hl=nl"
    - name: radboud
      url: "https://www.computationalpathologygroup.eu/members/daan-geijs/"

paginate: 5
menu:
  main:
  - name: Posts
    url: /posts/
    weight: -150
  - name: Media
    url: /media/
    weight: -135
  - name: Search
    url: /search/
    weight: -90
  - name: Tags
    url: /tags/
    weight: -110
  - name: Archive
    url: /archives/
    weight: -130
#  - name: Publications
#    url: /publications/
#    weight: -140
# disable for now

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false