[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"
[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[build.environment]
  HUGO_VERSION = "0.92.2"

#[[headers]]
#  for = "/*"
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"
#    Referrer-Policy = "strict-origin-when-cross-origin"
#    X-Content-Type-Options = "no-sniff"
#
#[[headers]]
#  for = "/favicon-*.png"
#    [headers.values]
#    Cache-Control = "public, max-age=31536000"
#
#[[headers]]
#  for = "/images/*"
#    [headers.values]
#    Cache-Control = "public, max-age=31536000"
